# theme: jekyll-theme-cayman
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Tg-Bootstrap]
description: [An isolated bootstrap version to avoid conflict with existing styles.]
show_downloads: "false"
# google_analytics: [Your Google Analytics tracking ID]
